development:
  adapter: postgresql
  encoding: unicode
  database: easy_shopping_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: easy_shopping_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: easy_shopping_production
  pool: 5